### ISSUE TITLE
As a patient, I want to specify illness information when submitting a case

### ISSUE THREAD

**Issue by KurtTaylan** [JUGIstanbul/second-opinion-api#36]
primary complaint
start date,
primary symptoms,
medication being used as a list of items,
primary body parts affected

**Comment by alidincerdere** [comment]
So in current Case structure we already have:
start date (illnessStartDate)
primary symptoms (symptoms)
medication being used as a list of items (treatments)

therefore "primary complaint" and "primary body parts affected" will be added in case structure @KurtTaylan
